// Admin is Japanese-only (docs/ui-conventions.md), so unlike the booking LP
// this doesn't need next-intl — a flat constants object is enough and keeps
// copy out of component bodies per the same doc's recommendation.
export const copy = {
  nav: {
    dashboard: "ダッシュボード",
    calendar: "予約カレンダー",
    needsReview: "要確認予約",
    manualEntry: "手動予約入力",
    inventory: "在庫管理",
    settingsGroup: "設定",
    seatingPlans: "予約プラン",
    tables: "テーブル管理",
    restaurant: "店舗基本設定",
    users: "ユーザー管理",
    lpCustomization: "LPカスタマイズ",
    notifications: "通知設定",
    auditLog: "監査ログ",
    logout: "ログアウト",
  },
  permission: {
    title: "権限がありません",
    body: "この機能を利用するにはadmin権限が必要です。必要な場合は管理者にお問い合わせください。",
  },
  login: {
    title: "omabo 管理画面",
    email: "メールアドレス",
    password: "パスワード",
    submit: "ログイン",
    mfaTitle: "認証コードを入力してください",
    mfaCode: "6桁のコード",
    mfaSubmit: "確認",
    mfaSetupTitle: "多要素認証の設定が必要です",
    mfaSetupBody: "super_admin アカウントは多要素認証(MFA)の設定が必須です。設定するまでこの画面をスキップできません。",
    mfaSetupConfirm: "MFAを設定して続ける",
  },
  dashboard: {
    title: "ダッシュボード",
    todayReservations: "本日の予約",
    needsReviewCount: "要確認の予約",
    goToCalendar: "予約カレンダーを見る",
    goToNeedsReview: "要確認一覧を見る",
    goToManualEntry: "手動で予約を登録",
    trendTitle: "予約数推移(直近21日間)",
    trendTotal: (n: number) => `合計 ${n}件`,
    trendAverage: (n: string) => `1日平均 ${n}件`,
  },
  calendar: {
    title: "予約カレンダー",
    viewMonth: "月",
    viewWeek: "週",
    viewDay: "日",
    noSlotsGenerated: "未設定",
    noSeatingPlan: "予約プランを設定してください",
    goToSeatingPlans: "予約プランの設定へ",
    needsReviewBadge: "要確認",
  },
  reservationDetail: {
    title: "予約詳細",
    superseded: "この予約は変更されました",
    viewNew: "新しい予約を見る",
    hasPrevious: "変更前の予約を見る",
    needsReviewReasonLabel: "要確認の理由",
    reasonInventoryConflict: "在庫競合",
    reasonLowConfidence: "解析の信頼度が低い",
    reasonPlanUnresolved: "プラン未確定",
    confirm: "確定する",
    reject: "却下する",
    cancel: "予約をキャンセル",
    cancelConfirm: "この予約をキャンセルしますか?",
    refundPendingNotice: "キャンセルは成立しました。返金は承認待ちです。",
    contactMasked: "権限の都合上、連絡先はマスクされています",
  },
  manualEntry: {
    title: "手動予約入力",
    subtitle: "電話予約はどんな状況でも断れないため、警告付きで登録を許可する画面です。",
    date: "日付",
    time: "時間",
    plan: "プラン",
    channelPhone: "電話",
    channelOta: "OTA",
    channelWalkIn: "ウォークイン",
    partySize: "人数",
    guestName: "氏名",
    guestPhone: "電話番号",
    guestEmail: "メールアドレス(任意)",
    notes: "備考",
    submit: "登録する",
    overCapacityWarning: "選択した時間枠の残席数を超えています。",
    forceSubmit: "それでも登録する",
    noPermission: "在庫を超える登録の権限がありません。以下の空いている時間枠をご検討ください。",
    suggestions: "空いている時間枠の候補",
    slotNotGenerated: "この日はまだ時間枠が生成されていません。",
    generateAndRegister: "時間枠を生成して登録",
    success: "予約を登録しました。",
  },
  seatingPlans: {
    title: "予約プラン",
    create: "+ 新規プラン作成",
    partyRange: "人数",
    dedicatedLabel: (capacity: number) => `${capacity}名(このプラン専用)`,
    sharedLabel: (partners: string) => `${partners}と定員を共有`,
    capacityHeading: "定員",
    timeHeading: "予約時間",
    totalCapacity: "総容量(同時に受け入れ可能な人数)",
    timeModelType: "時間の扱い方",
    fixed: "固定枠",
    flexible: "自由入力",
    fixedTimes: "受付時刻",
    addTime: "追加",
    startTime: "受付開始",
    endTime: "受付終了",
    intervalMinutes: "選択の区切り(分)",
    turnTimeMinutes: "回転時間(分)",
    save: "変更を保存",
    edit: "編集",
    editTimeModel: "時間設定を編集",
    hideTimeModel: "閉じる",
    dangerZoneTitle: "無効化・削除",
    currentUsage: (count: number) => `現在の予約数: ${count}件`,
    active: "有効",
    deactivate: "無効化する",
    activate: "有効化する",
    delete: "削除する",
    deleteConfirm: "このプランを削除しますか?この操作は取り消せません。",
    cannotDelete: "既存の予約があるため削除できません。無効化をご利用ください。",
    shareWith: "他のプランと共有する",
    makeDedicated: "共有をやめて専用にする",
    chooseSharePartner: "共有する相手のプランを選んでください",
    sharePreview: (capacity: number) =>
      `参加すると、両プランの合計予約人数がこの${capacity}名の上限を共有します。現在の専用設定は上書きされます。`,
    leavePrompt: "専用にする場合の新しい定員を設定してください。",
    impactWarning: (names: string) => `この定員は${names}とも共有しています。変更すると${names}の予約可能人数にも影響します。`,
    cannotChangeTimeModelType: "既存の予約があるため時間の扱い方(固定枠/自由入力)は変更できません。",
    cannotChangeShare: "既存の予約があるため共有設定は変更できません。",
  },
  createPlan: {
    title: "新規プラン作成",
    name: "プラン名",
    minPartySize: "最小人数",
    maxPartySize: "最大人数",
    capacityHeading: "定員をどうしますか?",
    dedicatedOption: "このプラン専用にする",
    shareOption: "既存のプランと共有する",
    sharePartnerLabel: "共有先",
    submit: "作成する",
  },
  tables: {
    title: "テーブル管理",
    create: "+ テーブルを追加",
    name: "テーブル名",
    seatCount: "席数",
    active: "有効",
    deactivate: "無効化する",
    activate: "有効化する",
    delete: "削除する",
    deleteConfirm: "このテーブルを削除しますか?この操作は取り消せません。",
    cannotDelete: "既存の予約が割り当てられているため削除できません。",
    save: "保存する",
    edit: "編集",
    cancel: "キャンセル",
    empty: "まだテーブルが登録されていません。",
  },
  calendarTable: {
    columnHeading: "卓",
    unassigned: "未割り当て",
    timelineTitle: "卓別タイムライン",
    timelineEmpty: "登録されているテーブルがありません。",
    timelineNote: "手動で割り当てた卓を目安として表示しています。空き状況の判定には使用していません。",
  },
  inventory: {
    title: "在庫管理",
    date: "日付",
    time: "時間",
    capacity: "総容量",
    booked: "予約済み",
    held: "決済処理中",
    remaining: "残席",
    stopSell: "売止",
    notGenerated: "未生成",
    generate: "生成する",
    stopSellNote: "売止にしても既存の予約は維持されます。",
    flexibleHeading: "自由入力の時間枠(重なり判定)",
    flexibleReservationsEmpty: "この日の予約はまだありません。",
    turnTimeNote: (minutes: number) => `1組あたり${minutes}分の滞在として重なりを判定しています。`,
    endsAt: "終了目安",
  },
  needsReview: {
    title: "要確認予約一覧",
    empty: "現在、要確認の予約はありません。",
    reasonInventoryConflict: "在庫競合",
    reasonLowConfidence: "解析の信頼度が低い",
    reasonPlanUnresolved: "プラン未確定",
    rawEmailLabel: "受信メール本文(原文)",
    candidatePlansLabel: "プラン候補",
    confirm: "確定する",
    reject: "却下する",
  },
  users: {
    title: "ユーザー管理",
    name: "氏名",
    email: "メールアドレス",
    role: "ロール",
    status: "状態",
    active: "有効",
    inactive: "無効",
    invite: "招待する",
    deactivate: "無効化する",
    activate: "有効化する",
    roleStaff: "staff",
    roleAdmin: "admin",
    roleSuperAdmin: "super_admin",
  },
  restaurantSettings: {
    title: "店舗基本設定",
    name: "店舗名",
    address: "住所",
    phone: "電話番号",
    email: "メールアドレス",
    timezone: "タイムゾーン",
    acceptingReservations: "オンライン予約を受け付ける",
    businessHours: "営業時間",
    closed: "定休",
    save: "保存する",
    saved: "保存しました。",
  },
  lpCustomization: {
    title: "LPカスタマイズ",
    displayName: "表示名",
    welcomeMessage: "ウェルカムメッセージ",
    accentColor: "アクセントカラー",
    save: "保存する",
    note: "この設定は予約LPの本番表示には反映されません(Phase 0のモック画面です)。",
  },
  notificationSettings: {
    title: "通知設定",
    newReservation: "新規予約時に通知する",
    cancellation: "キャンセル時に通知する",
    needsReview: "要確認予約が発生した時に通知する",
    dailySummary: "日次サマリーを送る",
    save: "保存する",
  },
  auditLog: {
    title: "監査ログ",
    empty: "まだ操作履歴がありません。",
    time: "日時",
    actor: "操作者",
    action: "操作内容",
    detail: "詳細",
  },
  common: {
    guests: (n: number) => `${n}名`,
    back: "戻る",
    channel: "チャネル",
  },
} as const;
